import type { Metadata } from 'next';

import './globals.css';

import Providers from './Providers';

export const metadata: Metadata = {
  title: '오늘의 워크로그',
  description: 'Generated by create next app',
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
